language: node_js
before_install:
  - npm install -g mocha
install: travis_wait make ENV=development
notifications:
  email: false
node_js:
  - "9"
  - "10"
os:
  - windows
  - linux
  - osx
env:
  - DB=nedb
  - DB=mongodb

jobs:
  include:
    - stage: Test
      services: mongodb
      before_script:
        - npm run test:config:$DB
        - cat config.json
      script:
        - npm run eslint
        - npx flow check
        - travis_retry npm run test