language: node_js
before_install:
  - npm install -g mocha typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
install:
  - travis_wait make ENV=development
notifications:
  email: false
node_js:
  - "12"
before_script:
  - npm run test:config:$DB
  - cat config.json
script:
  - npm run test

stages:
  - name: eslint
  - name: test
    if: commit_message !~ /(\[skip\-travis|no\-tests|skip\-tests\])/

jobs:
  include:
    - stage: eslint
      before_install:
        - npm install -g typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
      install: skip
      os: linux
      before_script: skip
      script:
        - npm run eslint || travis_terminate 1
    - stage: test
      env: DB=nedb
      os: linux
    - stage: test
      env: DB=mongodb
      services: mongodb
      os: linux
    - stage: test
      env: DB=nedb
      os: osx
