language: node_js
before_install:
  - npm install -g mocha
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
install:
  - travis_wait make ENV=development
notifications:
  email: false
services: mongodb
before_script:
  - npm run test:config:$DB
  - cat config.json
script:
  - npm run eslint
  - npx flow check
  - travis_retry npm run test

matrix:
  include:
    - os: linux
      node_js:
        - "9"
        - "10"
      env:
        - DB=nedb
        - DB=mongodb

    - os: windows
      node_js:
        - "9"
        - "10"
      env:
        - DB=nedb
        - DB=mongodb

    - os: osx
      env: DB=nedb
      node_js:
        - "9"
        - "10"