language: node_js
before_install:
  - npm install -g mocha standard
node_js:
  - "8"
  - "9"

jobs:
  include:
    - script: npm run standard
    - stage: NEDB
      node_js: "8"
      before_script: npm run test:config:nedb
      script: npm run test
    - stage: NEDB
      node_js: "9"
      before_script: npm run test:config:nedb
      script: npm run test
    - stage: MONGODB
      services: mongodb
      before_script: npm run test:config:mongodb
      script: npm run test
