language: node_js
services: mongodb
matrix:
  include:
    - node_js: "8"
    - node_js: "9"
before_install:
- npm install -g mocha standard

stages:
  - NEDB
  - MONGODB

jobs:
  include:
    - script: npm run standard
    - stage: NEDB
    - script: npm run test:config:nedb && npm run test
    - stage: MONGODB
    - script: npm run test:config:mongodb && npm run test
