language: node_js
before_install:
  - npm install -g mocha standard

node_js:
  - "9"

jobs:
  include:
    - script: npm run standard
    - stage: NEDB
    - script: npm run test:config:nedb && npm run test
    - stage: MONGODB
      services: mongodb
    - script: npm run test:config:mongodb && npm run test
