language: node_js
before_install:
  - npm install -g mocha
install: travis_wait make ENV=development
notifications:
  email: false

jobs:
  include:
    - stage: NEDB
    - node_js:
        - "9"
        - "10"
    - os:
        - windows
        - linux
      before_script:
        - npm run test:config:nedb
        - cat config.json
      script:
        - npm run eslint
        - npx flow check
        - travis_retry npm run test
    - stage: MONGODB
    - node_js:
        - "9"
        - "10"
    - os:
        - windows
        - linux
      services: mongodb
      before_script:
        - npm run test:config:mongodb
        - cat config.json
      script:
        - npm run eslint
        - npx flow check
        - travis_retry npm run test
