language: node_js
before_install:
  - yarn add mocha typescript --ignore-engines
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
install:
  - travis_wait make ENV=development
notifications:
  email: false
node_js:
  - "12"
before_script:
  - npm run test:config:$DB
  - cat config.json
script:
  - npm run test

stages:
  - name: test
    if: commit_message !~ /(\[skip\-travis|no\-tests|skip\-tests\])/

jobs:
  include:
    - stage: test
      env: DB=nedb
      os: linux
    - stage: test
      env: DB=mongodb
      services: mongodb
      os: linux