language: node_js
services: mongodb
node_js:
  - "8"
  - "9"
before_install:
- npm install -g mocha standard

jobs:
  include:
    - script: npm run standard
    - script: npm run test:config:nedb && npm run test
    - script: npm run test:config:mongodb && npm run test
