language: node_js
before_install:
- npm install -g mocha standard

stages:
  - STANDARD Compliance tests
  - NEDB
  - MONGODB

jobs:
  include:
    - script: npm run standard
      node_js: "9"
    - stage: NEDB
      node_js:
      - "8"
      - "9"
    - script: npm run test:config:nedb && npm run test
    - stage: MONGODB
      services: mongodb
      node_js:
      - "8"
      - "9"
    - script: npm run test:config:mongodb && npm run test
