language: node_js
before_install:
  - npm install -g mocha
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
install:
  - travis_wait make ENV=development
notifications:
  email: false
node_js:
  - "11"
os:
  - linux
  - osx
env:
  - DB=nedb
  - DB=mongodb
services: mongodb
before_script:
  - npm run test:config:$DB
  - cat config.json
script:
  - npm run tslint
  - travis_retry npm run test

matrix:
  if: commit_message !~ /(\[skip-travis\])/
  exclude:
    - os: osx
      env: DB=mongodb