language: node_js
before_install:
  - npm install -g mocha
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
install:
  - travis_wait make ENV=development
notifications:
  email: false
node_js:
  - "11"
before_script:
  - npm run test:config:$DB
  - cat config.json
script:
  - commitlint-travis
  - npm run tslint
  - travis_retry npm run test

stages:
  - name: skip
    if: commit_message =~ /(\[skip\-travis|no\-tests|skip\-tests\])/
  - name: test
    if: commit_message !~ /(\[skip\-travis|no\-tests|skip\-tests\])/

jobs:
  include:
    - stage: skip
      before_install: skip
      install: skip
      os: linux
      before_script: skip
      script: echo 'Found skip tag. Skipping tests.'
    - stage: test
      env: DB=nedb
      os: linux
    - stage: test
      env: DB=mongodb
      services: mongodb
      os: linux
    - stage: test
      env: DB=nedb
      os: osx
