commit_message: '[skip-tests]'
preserve_hierarchy: true

files:
  - source: /locales/en.json
    translation: /locales/%two_letters_code%.json
  - source: /locales/en/**/*
    translation: /locales/%two_letters_code%/**/%original_file_name%

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
