name: Changelog test

on:
  push:
    branches:
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # load full history

      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: deps
        run: ENV=development make dependencies

      - name: Generate changelog
        id: log
        run: echo ::set-output name=MESSAGE::$(node tools/changelog.js --escape generate)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: SOGEBOT ${{ github.ref }}
          body: |
            ${{ steps.log.outputs.MESSAGE }}
          draft: false
          prerelease: false
