name: Crowdin Action

on:
  pull_request:
  #push:
  #  branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.5
      with:
        upload_translations: true
        download_translations: true

        # This is the name of the git branch that Crowdin will create when opening a pull request.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        localization_branch_name: l10n_crowdin_action
        create_pull_request: true

        # dry run to test
        dryrun_action: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        CROWDIN_PROJECT_ID: 400078
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
