name: Crowdin Action

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* */1 * * *" # run every hour

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.5
      with:
        upload_sources: true
        upload_sources_args: '--verbose'
        crowdin_branch_name: master

        # This is the name of the git branch that Crowdin will create when opening a pull request.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        localization_branch_name: l10n_crowdin_action
        download_translations: true
        create_pull_request: true
        pull_request_title: 'chore(locales): crowdin update'
        pull_request_body: '[skip-tests]'

        # dry run to test
        # dryrun_action: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
