name: Crowdin Action

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours
  pull_request:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.8
      with:
        upload_sources: true
        upload_sources_args: '--verbose'
        crowdin_branch_name: master

        download_translations: true
        download_translations_args: '--all'

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: git shenanigans
      run: |
        ls -sh locales/

