name: Unused dependency check

on:
  push:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install minimal dependencies
        run: npm install lodash

      - name: Run dependency check
        run: node tools/dependency.js