name: Unused dependency check

on:
  push:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "pullrequest-artifact.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install minimal dependencies
        run: npm install lodash

      - name: Run dependency check
        run: node tools/dependency.js