name: Docker Image CI - release

on:
  project_column:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: "sogehige/sogebot"
          TAG_NAME: ${{ github.ref }}
          LATEST: "true"
