name: Nightlies

concurrency:
  group: nightlies-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # load full history
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: install node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Install latest npm
        run: |
          npm install -g npm

      - name: Build a bot
        run: NODE_MODULES_DIR=./node_modules make

      - name: Zip a bot
        run: make pack

      - uses: actions/upload-artifact@v2
        with:
          name: sogeBot-${{ steps.slug.outputs.sha8 }}
          path: ${{ github.workspace }}/*.zip

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            sogebot/nightly:latest
            sogebot/nightly:${{ github.sha }}