name: Docker Image CI - nightly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Push to GitHub Package with shasum
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: "sogehige/sogebot"
          TAG_NAME: nightly:${{ github.sha }}
      - name: Build & Push to GitHub Package as latest
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: "sogehige/sogebot"
          TAG_NAME: nightly:latest
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.2.8
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "sogebot/nightly"
          TAG_NAME: ${{ github.sha }}
          LATEST: "true"

