name: Tests

on:
  push:


env:
  TAG: ${{format(github.ref, 'refs/tags/', '')}}
  HEAD: ${{format(github.ref, 'refs/heads/', '')}}

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: GITHUB ref
      run: echo '${{github.ref}}'
    - name: GITHUB tag
      run: echo $TAG
    - name: GITHUB head
      run: echo $HEAD

