name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: All test should be run - tests are not containing describe.only
      run: |
          if ! grep -r -l 'describe.only' ./test/; then
            exit 0
          else
            exit 1
          fi;
    - name: install node v13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Install eslint and dependencies
      run: npm install typescript eslint jsonlint-mod @typescript-eslint/parser @typescript-eslint/eslint-plugin --only=dev
    - name: Run eslint
      run: make eslint
    - name: Run jsonlint
      run: make jsonlint
  nedb:
    name: NeDB tests
    if: contains(github.event.pull_request.body, '[skip-tests]') != true
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Install all dependencies
      run: make
    - name: Set proper db to use
      run: npm run test:config:nedb
    - name: Run mocha
      run: npm test
  nedb2:
    name: NeDB tests
    if: contains(github.event.pull_request.body, '[skip-tests]') == true
    runs-on: ubuntu-latest
    steps:
    - name: Skipped OK
      run: 'echo "[skip-tests] found"'
  mongodb:
    name: MongoDB tests
    if: contains(github.event.pull_request.body, '[skip-tests]') != true
    needs: eslint
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install node v13
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install all dependencies
      run: make
    - name: Set proper db to use
      run: npm run test:config:mongodb
    - name: Run mocha
      run: npm test
  mongodb2:
    name: MongoDB tests
    if: contains(github.event.pull_request.body, '[skip-tests]') == true
    runs-on: ubuntu-latest
    steps:
    - name: Skipped OK
      run: 'echo "[skip-tests] found"'