name: SQLite tests

concurrency:
  group: sqlite-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  migration:
    name: SQLite tests - migration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: log
      name: Load commit message for skip test check
      run: echo "MESSAGE=$(git log --no-merges -1 --pretty=format:%s%b)" >> $GITHUB_OUTPUT
    - name: install node v18
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install latest npm
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: |
        npm install --location=global npm
    - name: Install all dependencies and build just a bot
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: ENV=development NODE_MODULES_DIR=./node_modules make info clean dependencies bot
    - name: Set proper db to use
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: npm run test:config:sqlite
    - name: Run migration test
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: npm run test:migration
  sqlite:
    name: SQLite tests - part 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: log
      name: Load commit message for skip test check
      run: echo "MESSAGE=$(git log --no-merges -1 --pretty=format:%s%b)" >> $GITHUB_OUTPUT
    - name: install node v18
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install latest npm
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: |
        npm install --location=global npm
    - name: Install all dependencies and build just a bot
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: ENV=development NODE_MODULES_DIR=./node_modules make info clean dependencies bot
    - name: Set proper db to use
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: npm run test:config:sqlite
    - name: Run mocha
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: TESTS=@func1 npm test
    - uses: codecov/codecov-action@v3
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-sqlite # optional
        flags: sqlite
  sqlite2:
    name: SQLite tests - part 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: log
      name: Load commit message for skip test check
      run: echo "MESSAGE=$(git log --no-merges -1 --pretty=format:%s%b)" >> $GITHUB_OUTPUT
    - name: install node v18
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install latest npm
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: |
        npm install --location=global npm
    - name: Install all dependencies and build just a bot
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: ENV=development NODE_MODULES_DIR=./node_modules make info clean dependencies bot
    - name: Set proper db to use
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: npm run test:config:sqlite
    - name: Run mocha
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: TESTS=@func2 npm test
    - uses: codecov/codecov-action@v3
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-sqlite # optional
        flags: sqlite
  sqlite3:
    name: SQLite tests - part 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: log
      name: Load commit message for skip test check
      run: echo "MESSAGE=$(git log --no-merges -1 --pretty=format:%s%b)" >> $GITHUB_OUTPUT
    - name: install node v18
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install latest npm
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: |
        npm install --location=global npm
    - name: Install all dependencies and build just a bot
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: ENV=development NODE_MODULES_DIR=./node_modules make info clean dependencies bot
    - name: Set proper db to use
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: npm run test:config:sqlite
    - name: Run mocha
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      run: TESTS=@func3 npm test
    - uses: codecov/codecov-action@v3
      if: "!contains(steps.log.outputs.MESSAGE, '[skip-tests]')"
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-sqlite # optional
        flags: sqlite